### ISSUE TITLE
instead of saving individual csv's we will update one

### ISSUE THREAD

**Issue by DrAtomic** [jb-codemaker/ECE_Team9_Capstone#24]

**Comment by jb-codemaker** [comment]
Why truncate to one?  We could add to neighboring columns in one file but it would have it's own time scale anyway.

**Comment by DrAtomic** [comment]
this is a good point. i was just thinking it would be easier for for jinghan to graph the data if it were one file. It might not be important though

**Comment by DrAtomic** [comment]
keeping it as separate csvs
